version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  environment:
    HEROKU_APP_NAME: polaris-backend-express
    HEROKU_API_KEY: 95262926-8038-4182-b3a7-f0827f4a418c
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git